server:
  port: 8080

spring:
  application:
    name: transaction-gateway
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

management:
  endpoints:
    web:
      exposure:
        include: health,info

fraud:
  kafka:
    topics:
      transactions: ${TRANSACTIONS_TOPIC:transactions.raw}
